"""add fund_applications and fund_site_configs

Revision ID: cda774b43b10
Revises: a1b2c3d4e5f6
Create Date: 2026-02-15 16:13:25.588905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cda774b43b10'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('fonds_id', sa.Uuid(), nullable=True),
    sa.Column('fonds_nom', sa.String(length=255), nullable=False),
    sa.Column('fonds_institution', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('url_candidature', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fonds_id'], ['fonds_verts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_site_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fonds_id', sa.Uuid(), nullable=False),
    sa.Column('url_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fonds_id'], ['fonds_verts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_action_plans_type'), table_name='action_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_action_plans_type'), 'action_plans', ['entreprise_id', 'type_plan', 'created_at'], unique=False)
    op.drop_table('fund_site_configs')
    op.drop_table('fund_applications')
    # ### end Alembic commands ###
