"""create_intermediaires_table

Revision ID: effc4cfeb230
Revises: e7f8a9b0c1d2
Create Date: 2026-02-16 01:59:54.376592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'effc4cfeb230'
down_revision: Union[str, Sequence[str], None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intermediaires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fonds_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('site_web', sa.String(length=500), nullable=True),
    sa.Column('url_formulaire', sa.String(length=500), nullable=True),
    sa.Column('type_soumission', sa.String(length=30), nullable=True),
    sa.Column('instructions_soumission', sa.Text(), nullable=True),
    sa.Column('documents_requis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('etapes_specifiques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delai_traitement', sa.String(length=50), nullable=True),
    sa.Column('est_recommande', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fonds_id'], ['fonds_verts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intermediaires')
    # ### end Alembic commands ###
