"""initial tables

Revision ID: fbcfdc6a82d8
Revises: 
Create Date: 2026-02-13 01:19:06.730805

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbcfdc6a82d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referentiels_esg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('grille_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('entreprises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('secteur', sa.String(length=100), nullable=True),
    sa.Column('sous_secteur', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('effectifs', sa.Integer(), nullable=True),
    sa.Column('chiffre_affaires', sa.Numeric(), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profil_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fonds_verts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('referentiel_id', sa.Uuid(), nullable=True),
    sa.Column('montant_min', sa.Numeric(), nullable=True),
    sa.Column('montant_max', sa.Numeric(), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('secteurs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pays_eligibles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criteres_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('url_source', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiels_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('lien', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('sector_benchmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('secteur', sa.String(length=100), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('referentiel_id', sa.Uuid(), nullable=True),
    sa.Column('score_e_moyen', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_s_moyen', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_g_moyen', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_global_moyen', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('carbone_moyen_tco2e', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nombre_entreprises', sa.Integer(), nullable=True),
    sa.Column('periode', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiels_esg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secteur', 'pays', 'referentiel_id', 'periode', name='idx_benchmark_unique')
    )
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('handler_key', sa.String(length=100), nullable=False),
    sa.Column('handler_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('action_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=True),
    sa.Column('referentiel_id', sa.Uuid(), nullable=True),
    sa.Column('score_initial', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_cible', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiels_esg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_footprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('energie', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transport', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dechets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('achats', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_tco2e', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_carbon_entreprise', 'carbon_footprints', ['entreprise_id', 'annee', 'mois'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('score_solvabilite', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_impact_vert', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_combine', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('donnees_financieres_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('donnees_esg_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('donnees_declaratives_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('facteurs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('type_mime', sa.String(length=100), nullable=True),
    sa.Column('chemin_stockage', sa.String(length=500), nullable=False),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('texte_extrait', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esg_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entreprise_id', sa.Uuid(), nullable=False),
    sa.Column('referentiel_id', sa.Uuid(), nullable=True),
    sa.Column('score_e', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_s', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_global', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiels_esg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'referentiel_id', 'created_at', name='idx_score_per_referentiel')
    )
    op.create_table('fonds_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fonds_id', sa.Uuid(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('type_info', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fonds_id'], ['fonds_verts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fonds_chunks_embedding', 'fonds_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('action_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priorite', sa.String(length=20), nullable=True),
    sa.Column('pilier', sa.String(length=20), nullable=True),
    sa.Column('critere_id', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('impact_score_estime', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cout_estime', sa.Numeric(), nullable=True),
    sa.Column('benefice_estime', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_items_plan', 'action_items', ['plan_id', 'statut'], unique=False)
    op.create_table('doc_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_chunks_embedding', 'doc_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_doc_chunks_embedding', table_name='doc_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('doc_chunks')
    op.drop_index('idx_action_items_plan', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('idx_fonds_chunks_embedding', table_name='fonds_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('fonds_chunks')
    op.drop_table('esg_scores')
    op.drop_table('documents')
    op.drop_table('credit_scores')
    op.drop_table('conversations')
    op.drop_index('idx_carbon_entreprise', table_name='carbon_footprints')
    op.drop_table('carbon_footprints')
    op.drop_table('action_plans')
    op.drop_table('skills')
    op.drop_table('sector_benchmarks')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('fonds_verts')
    op.drop_table('entreprises')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('report_templates')
    op.drop_table('referentiels_esg')
    # ### end Alembic commands ###
